[package]
name = "synth"
version = "0.1.0"
edition = "2021"

[lib]
name = "synth"
crate-type = ["cdylib", "rlib"]

[[bin]]
name = "synth-native"
path = "src/main.rs"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
winit = "0.28.0"
rand = "0.8"
itertools = "0.14.0"
hound = "3.5.0"  # For writing .wav files
egui = "0.28"
eframe = { version = "0.28", default-features = false, features = ["glow", "default_fonts"] }
anyhow = "1"
rfd = "0.14"
instant = "0.1.13"
log = "0.4"

# --- native-only ---
[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
cpal = "0.15"
crossterm = "0.27"
pollster = "0.4"

# --- wasm-only ---
[target.'cfg(target_arch = "wasm32")'.dependencies]
cpal = { version = "0.15.3", features = ["wasm-bindgen"] }
wasm-bindgen = "0.2"
wasm-bindgen-futures = "0.4"
console_error_panic_hook = "0.1"
console_log = "1.0"
getrandom = { version = "0.2", features = ["js"] }

