[package]
name = "synth-core"
version.workspace = true
edition.workspace = true
authors.workspace = true

[lib]
name = "synth_core"
crate-type = ["rlib"]

[dependencies]
serde.workspace = true
serde_json.workspace = true
rand.workspace = true
itertools.workspace = true
hound.workspace = true
anyhow.workspace = true
log.workspace = true
arc-swap.workspace = true
num-traits.workspace = true

# Optional GUI support
egui = { workspace = true, optional = true }

[features]
default = []
egui-support = ["egui"]

# Audio playback
[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
cpal.workspace = true

[target.'cfg(target_arch = "wasm32")'.dependencies]
cpal = { version = "0.15.3", features = ["wasm-bindgen"] }
